M48
; DRILL file {KiCad 7.0.5} date Mon Jul 17 11:59:11 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-07-17T11:59:11-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.5
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X122.0Y-74.0
X122.0Y-119.0
X148.0Y-74.0
X148.0Y-119.0
T0
M30
